spring:
  profiles:
    active:
    - dev
--- 
server:
  port: 8201
spring:
  profiles: test
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
--- 
server:
  port: 8202
spring:
  profiles: dev
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001111111/eureka/
--- 
server:
  port: 8203
spring:
  profiles: default
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-default.com:7001/eureka/